export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const IS_AUTHENTICATED_SUCCESS = "IS_AUTHENTICATED_SUCCESS";
export const IS_AUTHENTICATED_FAIL = "IS_AUTHENTICATED_FAIL";
export const LOGOUT = "LOGOUT";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const IS_AUTHENTICATED_REQUEST = "IS_AUTHENTICATED_REQUEST";
